[package]
name = "attn_rust"
version = "0.1.0"
authors = ["Sam Stevens <stevens.994@osu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
